#include "gpio.h"

const gpio_ConfigType gpio_initialConfiguration_s =
{
      {   /* PORT A */
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PA0,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PA1,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PA2,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PA3,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PA4,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PA5,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PA6,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PA7,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },

       /* PORT B */
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PB0,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PB1,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PB2,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PB3,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PB4,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PB5,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PB6,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PB7,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },

      /* PORT C */
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PC0,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PC1,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PC2,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PC3,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PC4,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PC5,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PC6,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PC7,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },

      /* PORT D */
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PD0,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PD1,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PD2,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PD3,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PD4,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PD5,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PD6,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PD7,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },

      /* PORT E */
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PE0,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PE1,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PE2,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PE3,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PE4,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PE5,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PE6,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PE7,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },

      /* PORT F */
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PF0,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PF1,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PF2,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PF3,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PF4,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PF5,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PF6,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PF7,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },

      /* PORT G */
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PG0,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PG1,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PG2,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PG3,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PG4,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PG5,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PG6,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            },
            {
                  GPIO_TRUE,
                  GPIO_CHANNEL_PG7,
                  GPIO_OUTPUT,
                  GPIO_PIN_INITIAL_HIGH
            }
      }
};





const void *gpio_getlcfgdata(void)
{
   return ((void*) &gpio_initialConfiguration_s);
}
